# 問題 ID (必須: 出力 html 名にも使用される)
id = "I"

# 制約の出力先となるファイル名
params_path = "./tests/constraints.hpp"

# 添付ファイルが格納されているフォルダ名
assets_path = "./statement/assets/"

# 問題文が格納されている場所
# 問題文ファイルがローカルにある場合、Markdown ファイルへのパスを記載する
[[statements]]
path = "./statement/statement.md"
lang = "ja"
markdown_extensions = ["md_in_html", "tables", "fenced_code"]

# 問題制約を書く
[constraints]
MIN_N = 1
MAX_N = 10000
