name: docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Fetch tags and branches
        run: |
          git fetch -t --all
          git branch master origin/master

      - name: Build documentation
        run: sphinx-polyversion --sequential docs/poly.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-build
          path: docs/_build
          retention-days: 7

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dry-run: true
          local-dir: ./docs/_build
          server-dir: ./docs/statements-manager
