name: test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip3 install --upgrade setuptools
          pip3 install .[dev]

      - name: Run tests
        run: |
          ss-manager -h
          pytest -v
        shell: bash

  test-python-3-9-2:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9.2
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.2"

      - name: Install dependencies
        run: |
          pip3 install --upgrade setuptools
          pip3 install .[dev]

      - name: Run tests
        run: |
          ss-manager -h
          pytest -v
        shell: bash